import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";
// import {ClerkProvider} from "@clerk/nextjs"

// Import Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100","200","300","400", "500", "600", "700"], // Customize weights as needed
  display: "swap",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      // <ClerkProvider>
    <html lang="en">
      <body
        className={`${poppins.className}  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
        <Header />
        <main>{children}</main>
       <Footer />
       </StoreProvider>
      </body>
    </html>
      // {/* </ClerkProvider> */}
  );
}
